### PR TITLE
Sync with AnacondaRecipes

### PR DESCRIPTION
**Pull request by jjhelmus**
sync recipe with AnacondaRecipes to pick up recommended changes for use with conda-build 3.  

No build number change as the contents of the package should not change.

### CODE REVIEW

**Comment by ocefpaf** [comment]
My guess is that we need to re-render to get the temporary compiler workaround to work, right?

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
> My guess is that we need to re-render to get the temporary compiler workaround to work, right?

I think so, triggered.

**Comment by ocefpaf** [comment]
We need to fix the linter there `requirements/build` is before `requirements/run`.

**Comment by jjhelmus** [comment]
Agreed, having `requirements/build` before `requirements/host` isn't a bad idea and I think would quite the linter.

**Comment by ocefpaf** [comment]
Thanks @jjhelmus!

**Pull request merged**
